apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-api
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: payment-api
  namespaceSelector:
    matchNames:
      - payments
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
