apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: payments
  labels:
    app: payment-api
spec:
  selector:
    app: payment-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
